# Generated by Django 4.2 on 2024-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='感謝のフレーズ')),
                ('category', models.CharField(choices=[('daily', '日常'), ('work', '仕事'), ('praise', '褒められたとき')], max_length=20, verbose_name='ジャンル')),
            ],
        ),
    ]
