# Generated by Django 4.2 on 2023-04-16 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('hours_of_sleep', models.IntegerField(verbose_name='睡眠時間')),
                ('sleep_quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='睡眠の質')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('朝ごはん', '朝ごはん'), ('昼ごはん', '昼ごはん'), ('夜ごはん', '夜ごはん'), ('おやつ', 'おやつ')], max_length=4)),
                ('bean', models.BooleanField(verbose_name='ま：まめ')),
                ('sesame', models.BooleanField(verbose_name='ご：ごま')),
                ('seaweed', models.BooleanField(verbose_name='わ：海藻')),
                ('vegetable', models.BooleanField(verbose_name='や：野菜')),
                ('fish', models.BooleanField(verbose_name='さ：さかな')),
                ('mushroom', models.BooleanField(verbose_name='し：きのこ')),
                ('potato', models.BooleanField(verbose_name='い：いも')),
                ('fresh_vegetable', models.BooleanField(verbose_name='生：生野菜')),
                ('fermented_food', models.BooleanField(verbose_name='発酵：発酵食品')),
                ('memo', models.TextField()),
                ('photo', models.ImageField(upload_to='meal_photos/')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('supplement', models.ManyToManyField(to='diary.supplement')),
            ],
        ),
    ]
