# Generated by Django 4.2 on 2023-04-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_meal_diary_meal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary', to_field='date', verbose_name='日付'),
        ),
    ]
