# Generated by Django 4.2 on 2023-06-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_memo_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='morning_walking',
            field=models.BooleanField(default=False, verbose_name='朝の散歩'),
            preserve_default=False,
        ),
    ]
