# Generated by Django 4.2 on 2023-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_morning_walking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='morning_walking',
            field=models.IntegerField(choices=[(10, '10分'), (20, '20分'), (30, '30分'), (40, '40分'), (50, '50分'), (60, '60分')], verbose_name='朝の散歩'),
        ),
    ]
