# Generated by Django 4.2 on 2023-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diary_morning_walking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularExpressionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='言葉')),
                ('description', models.TextField(verbose_name='説明')),
            ],
        ),
        migrations.AlterField(
            model_name='diary',
            name='morning_walking',
            field=models.IntegerField(blank=True, choices=[(10, '10分'), (20, '20分'), (30, '30分'), (40, '40分'), (50, '50分'), (60, '60分')], null=True, verbose_name='あさんぽ'),
        ),
    ]
