# Generated by Django 4.2 on 2025-08-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfort_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfortaction',
            name='category',
        ),
        migrations.AddField(
            model_name='comfortaction',
            name='categories',
            field=models.ManyToManyField(to='comfort_list.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('heart', '🌱 心'), ('body', '🍔 からだ'), ('space', '🏠 空間'), ('time', '⏰ 時間'), ('mind', '💡 思考'), ('relationship', '🧸 人間関係'), ('hobby', '🌻 好きなこと'), ('self', '💝 自分')], max_length=20, unique=True),
        ),
    ]
