# Generated by Django 4.2 on 2025-11-09 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickledVegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable_type', models.CharField(choices=[('cucumber', 'きゅうり🥒'), ('eggplant', 'なす🍆'), ('carrot', 'にんじん🥕'), ('cabbage', 'キャベツ🥬'), ('pepper', 'ピーマン🌶️'), ('tomato', 'トマト🍅'), ('radish', 'だいこん🌶️'), ('turnip', 'かぶ🌰'), ('other', 'その他🥗')], max_length=20, verbose_name='野菜の種類')),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='カスタム名')),
                ('pickled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='漬けた日時')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='取り出した日時')),
                ('reminder_24h_sent', models.BooleanField(default=False, verbose_name='24時間リマインド送信済み')),
                ('reminder_48h_sent', models.BooleanField(default=False, verbose_name='48時間リマインド送信済み')),
                ('reminder_72h_sent', models.BooleanField(default=False, verbose_name='72時間リマインド送信済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ぬか漬け野菜',
                'verbose_name_plural': 'ぬか漬け野菜',
                'ordering': ['-pickled_at'],
            },
        ),
    ]
